# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: dotnet-frontend"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-backend
  labels:
    app: dotnet
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet
      tier: backend
  template:
    metadata:
      labels:
        app: dotnet
        tier: backend
    spec:
      initContainers:
      - name: init-db-ready
        image: mongo:4
        command: ['/bin/sh', '-c']
        args:
          - echo "Waiting for mongodb at dotnet-mongodb:27017 to go live before the BE..."; 
          - until (mongo --host dotnet-mongodb:27017 >/dev/null) do echo "Waiting for connection for 2 sec."; sleep 2; done
      containers:
      - name: backend
        image: dotnet-backend
        ports:
        - name: http-server
          containerPort: 8080
        - name: debug
          containerPort: 9229
        env:
        - name: PORT
          value: "8080"
        - name: DB_ADDR
          value: dotnet-mongodb:27017
