apiVersion: v1
kind: Service
metadata:
  name: rust-backend
  labels:
    app: rust
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: rust
    tier: backend
  ports:
  - port: 8080
    targetPort: http-server
