apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf.template: |
    #user nginx;
    #worker_processes  1;
    #events {
    #  worker_connections  10240;
    #}
    #http {
      server {
          listen       80;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html;
            try_files $uri$args $uri$args/ /index.html;
            include  /etc/nginx/mime.types;
          }

          location /game/ {
            #proxy_pass http://dotnet-backend:8080/game/;
            proxy_pass http://${BACKEND_API_ADDR}:${BACKEND_PORT}/game/;
          }
      }
    #}