# The app is configured to use skaffold modules.
# The backend to switch implementation and can be switched easily.
# To learn more about skaffold modules and multi-config support,
# visit https://skaffold.dev/docs/design/config/

apiVersion: skaffold/v4beta13
kind: Config
build:
  local:
    concurrency: 0
requires:
  - path: ./dotnet/src
  - path: ./rust
