# This Service manifest defines:
# - a load balancer for pods matching label "app: backend"
# - exposing the application to the public Internet (type:LoadBalancer)
# - routes port 80 of the load balancer to the port 8080 of the Pods.
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: v1
kind: Service
metadata:
  name: dotnet-backend
  labels:
    app: dotnet
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: dotnet
    tier: backend
  ports:
  - port: 8080
    targetPort: http-server