# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: dotnet-frontend"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-frontend
  labels:
    app: dotnet
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet
      tier: frontend
  template:
    metadata:
      labels:
        app: dotnet
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: dotnet-frontend
        ports:
        - name: http-server
          containerPort: 8080
        - name: debug
          containerPort: 9229
        env:
        - name: PORT
          value: "8080"
        - name: API_ADDR
          value: dotnet-backend
