name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the frontend dotnet Docker image
      run: docker build --file src/frontend/dotnet/Dockerfile --tag minesweeper/frontend/dotnet:$(date +%s) src/frontend/dotnet
    - name: Build the backend dotnet Docker image
      run: docker build --file src/backend/dotnet/src/Dockerfile --tag minesweeper/backend/dotnet:$(date +%s) src/backend/dotnet/src
    - name: Build the frontend angular Docker image
      run: docker build --file src/frontend/angular/Dockerfile --tag minesweeper/frontend/dotnet:$(date +%s) src/frontend/angular
