name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the frontend Docker image
      run: docker build --file src/frontend/Dockerfile --tag minesweeper/frontend:$(date +%s) src/frontend
    - name: Build the backend Docker image
      run: docker build --file src/backend/Dockerfile --tag minesweeper/backend:$(date +%s) src/backend
